name: frontend
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  graphql_flutter: ^5.1.0
  intl: ^0.17.0
  beamer: ^1.4.1+1
  timezone: ^0.8.0
  grouped_list: ^4.2.0
  flutter_slidable: ^1.2.0
  equatable: ^2.0.3
  socket_io: ^1.0.1
  syncfusion_flutter_calendar: ^20.1.50
  flutter_login: ^3.2.0
  shared_preferences: ^2.0.13
  formz: ^0.4.1
  logger: ^1.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
